version: '3'

services:
  news:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      HTTP_LISTEN: "8080"
      POSTGRES_DSN: "postgresql://user:password@postgres:5432/news?sslmode=disable"

  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: "news"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migration:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
    driver: local
