version: '3'

services:
  postgres:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_DB: "news"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data
      - ./migration:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
    driver: local
